### PR TITLE
Avoid Stack_overflow being raised

### PR DESCRIPTION
**Pull request by Chris00**
See https://github.com/ocaml/MPP-language-blender/issues/24

### CODE REVIEW

**Comment by Chris00** [comment]
Supersedes https://github.com/ocaml/MPP-language-blender/pull/23

**Comment by pw374** [comment]
Thanks

**Comment by pw374** [comment]
@Chris00 would you like to have merge rights on this repo?

**Comment by Chris00** [comment]
Why not... but note however I do not have the time maintain/develop this package (so only small PRs will get merged and it would be good that Travis be activated).

**Comment by pw374** [comment]
I'm asking only for the smallest tasks. :)

**Pull request merged**
